# Generated by Django 4.1.4 on 2023-02-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_category_categorynews_news_delete_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Csv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("text", models.TextField()),
                ("labels", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="news",
            name="fakeortrue",
            field=models.BooleanField(default=True, verbose_name="Real"),
        ),
    ]
