# Generated by Django 4.1.4 on 2023-02-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_csv_alter_news_fakeortrue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="csv",
            old_name="labels",
            new_name="label",
        ),
    ]
