# Generated by Django 4.1.4 on 2023-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_csv"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
