# Generated by Django 4.1.4 on 2023-02-07 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_news_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("label", models.BooleanField(default=True, verbose_name="Real")),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
            ],
        ),
        migrations.AlterField(
            model_name="categorynews",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news.newss"
            ),
        ),
        migrations.DeleteModel(
            name="News",
        ),
    ]
