# Generated by Django 4.1.6 on 2023-02-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_news_alter_categorynews_news_delete_newss"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Csv",
        ),
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="news.category",
            ),
        ),
    ]
