# Generated by Django 4.1.6 on 2023-02-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0012_delete_csv_news_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
