# Generated by Django 4.1.6 on 2023-03-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0013_alter_news_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="models")),
                ("accuracy", models.FloatField()),
                ("train_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
