# Generated by Django 4.1.6 on 2023-04-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0014_mlmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MLModel",
        ),
        migrations.AlterField(
            model_name="news",
            name="label",
            field=models.BooleanField(default=True, verbose_name="True"),
        ),
    ]
